// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Category: typeof import('./components/Category.vue')['default']
    CategoryItem: typeof import('./components/CategoryItem.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoInput: typeof import('./components/TodoInput.vue')['default']
    TodoItem: typeof import('./components/TodoItem.vue')['default']
  }
}
